sudo: required
services:
  - docker
env:
  - IMAGE_VERSION=2.3.0-hadoop2.7 SPARK_URL=http://apache.mirrors.spacedump.net/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.7.tgz
  - IMAGE_VERSION=2.3.0-hadoop2.6 SPARK_URL=http://apache.mirrors.spacedump.net/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.6.tgz
  - IMAGE_VERSION=2.3.0-without-hadoop SPARK_URL=http://apache.mirrors.spacedump.net/spark/spark-2.3.0/spark-2.3.0-bin-without-hadoop.tgz  

script: ./build_image.sh
deploy:
  provider: script
  script: ./docker_push.sh
